import { useState } from 'react';
import { ArrowRight, Check, ChevronDown, Image as ImageIcon } from 'lucide-react';
import AnimatedSection from './AnimatedSection';
import type { DoorProduct } from '@/data/doorProducts';

const patioColours = [['White','#eee'],['Black','#151515'],['Bronze','#70513a'],['Custom',null]] as const;

export default function DoorProductPage({product}:{product:DoorProduct}) {
  const [open,setOpen]=useState(0);
  const patio=product.slug==='sliding-patio';
  return <main>
    <section className="py-14 sm:py-20 border-b border-brand-border"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><p className="text-sm text-brand-muted mb-8"><a href="/doors" className="hover:text-brand-orange">Doors</a> / {product.title}</p><div className="grid lg:grid-cols-2 gap-10 items-center"><AnimatedSection><h1 className="text-4xl sm:text-5xl font-bold">{product.title}</h1><p className="text-lg text-brand-muted leading-relaxed mt-5">{product.short}</p><a href="/#quote" className="mt-7 inline-flex gap-2 items-center bg-brand-orange px-7 py-4 rounded-full font-medium">Get a Free Quote <ArrowRight size={16}/></a></AnimatedSection><div className="aspect-[4/3] bg-brand-card border border-brand-border rounded-3xl flex items-center justify-center overflow-hidden">{product.image?<img src={product.image} alt={product.title} className="w-full h-full object-contain"/>:<div className="text-center text-brand-muted"><ImageIcon className="mx-auto mb-3"/><p>Product image to be added</p></div>}</div></div></div></section>

    <section className="py-16 bg-brand-surface border-y border-brand-border"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid lg:grid-cols-2 gap-12"><AnimatedSection><p className="text-brand-orange text-xs uppercase tracking-[.2em] mb-3">Product overview</p><h2 className="text-3xl font-bold mb-5">What Is This Door?</h2><p className="text-brand-muted leading-relaxed">{product.explanation}</p></AnimatedSection><AnimatedSection delay={.08}><h2 className="text-3xl font-bold mb-6">Benefits of {product.title}</h2><ul className="space-y-4">{product.benefits.map(x=><li key={x} className="flex gap-3 text-brand-muted"><Check className="text-brand-orange shrink-0" size={18}/>{x}</li>)}</ul></AnimatedSection></div></section>

    <section className="py-16"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold mb-8">Why Choose INCO</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{['Construction quality','Insulation & weather sealing','Hardware & durability','Installation & warranty'].map(x=><div key={x} className="bg-brand-card border border-brand-border rounded-2xl p-5"><h3 className="font-semibold">{x}</h3><p className="text-sm text-brand-muted mt-2">Product-specific details to be finalized.</p></div>)}</div></div></section>

    <section className="py-16 bg-brand-surface border-y border-brand-border"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid lg:grid-cols-2 gap-10"><div><h2 className="text-3xl font-bold mb-7">Photos</h2><div className="grid grid-cols-2 gap-4">{[1,2,3].map(n=><div key={n} className={`${n===1?'col-span-2 aspect-[16/9]':'aspect-square'} bg-brand-card border border-brand-border rounded-2xl flex items-center justify-center text-sm text-brand-muted`}>Photo {n} to be added</div>)}</div></div><div><h2 className="text-3xl font-bold mb-7">Frequently Asked Questions</h2><div className="space-y-3">{product.faq.map(([q,a],i)=><div key={q} className="bg-brand-card border border-brand-border rounded-2xl"><button onClick={()=>setOpen(open===i?-1:i)} className="w-full text-left p-5 flex justify-between gap-4"><span>{q}</span><ChevronDown className={`shrink-0 transition-transform ${open===i?'rotate-180':''}`} size={18}/></button>{open===i&&<p className="px-5 pb-5 text-sm text-brand-muted">{a}</p>}</div>)}</div></div></div></section>

    <section className="py-16"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold mb-8">Additional Options / Information</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{['Glazing options','Hardware','Installation Type','Finishes'].map(x=><div key={x} className="bg-brand-card border border-brand-border rounded-2xl p-5"><h3 className="font-semibold">{x}</h3><p className="text-sm text-brand-muted mt-2">Availability and product-specific details to be confirmed.</p></div>)}</div></div></section>

    {patio&&<><section className="py-16 bg-brand-surface border-y border-brand-border"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold">Sliding Patio Door Colours</h2><p className="text-brand-muted mt-3">Patio-specific colour availability must be confirmed for the selected product.</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-8">{patioColours.map(([n,c])=><div key={n} className="group flex flex-col items-center gap-2"><div className="w-full aspect-square rounded-xl border-2 border-brand-border flex items-center justify-center transition-all hover:scale-105 hover:border-white/20" style={c?{backgroundColor:c}:undefined}>{!c&&'+'}</div><span className="text-xs text-brand-muted">{n}</span></div>)}</div></div></section><section className="py-16"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold mb-8">Additional Patio Door Information</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{['Product overview','PVC patio door information','Glazing','Frame','Locks & hardware','Sizes & options'].map(x=><div key={x} className="bg-brand-card border border-brand-border rounded-2xl p-5"><h3 className="font-semibold">{x}</h3><p className="text-sm text-brand-muted mt-2">Confirmed product details to be finalized.</p></div>)}</div></div></section></>}

    <section className="py-20 border-t border-brand-border text-center"><h2 className="text-3xl sm:text-4xl font-bold">Ready to Find the Right Door for Your Home?</h2><a href="/#quote" className="mt-7 inline-flex gap-2 items-center bg-brand-orange px-7 py-4 rounded-full">Get a Free Quote <ArrowRight size={16}/></a></section>
  </main>;
}
